### ISSUE TITLE
incorrect target_link_libraries for UNIX and APPLE

### ISSUE THREAD

**Issue by ValentinMargraf** [karthickai/tflite#5]
thanks a lot for your code and youtube series, super helpful!
i think you did sth wrong in the CMakeLists. in 05_TFLite_Image_classification

inside the target_link_libraries for Unix and Apple
TFLiteCheck should be changed to TFLiteImageClassification

**Comment by karthickai** [comment]
Thank you. I will revert to correct CMakelists.txt. Issue occurred by latest commit.

**Comment by karthickai** [comment]
I'm not worked on edge TPU, Sorry!!
