### ISSUE TITLE
Segmentation fault copy image into the tensor

### ISSUE THREAD

**Issue by patProgrammer** [karthickai/tflite#7]
Hello,
i am getting an error when i want to build the project in the qt creator (cmake).

![image](https://user-images.githubusercontent.com/110916637/183671028-2b8049b3-714a-4483-994e-53105d4b9a13.png)

**Comment by karthickai** [comment]
Hi, Could you kindly check your model input and Input data?

**Comment by patProgrammer** [comment]
I downloaded another model and it worked. Apparently my model is faulty. Thanks
